### PR TITLE
loader/svg: Fix unintended use of `float_t` type

### PR DESCRIPTION
**Pull request by akien-mga**
This broke x86_32 GCC build on Linux and Windows with this error:
```
hirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp: In function 'bool _toColor(const char*, uint8_t*, uint8_t*, uint8_t*, char**)':
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:716:42: error: cannot convert 'float_t*' {aka 'long double*'} to 'float*'
  716 |         if (_parseNumber(&content, &hue, &th) && hue) {
      |                                          ^~~
      |                                          |
      |                                          float_t* {aka long double*}
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:106:73: note:   initializing argument 3 of 'bool _parseNumber(const char**, const char**, float*)'
  106 | static bool _parseNumber(const char** content, const char** end, float* number)
      |                                                                  ~~~~~~~^~~~~~
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:721:48: error: cannot convert 'float_t*' {aka 'long double*'} to 'float*'
  721 |             if (_parseNumber(&hue, &satuation, &ts) && satuation && *satuation == '%') {
      |                                                ^~~
      |                                                |
      |                                                float_t* {aka long double*}
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:106:73: note:   initializing argument 3 of 'bool _parseNumber(const char**, const char**, float*)'
  106 | static bool _parseNumber(const char** content, const char** end, float* number)
      |                                                                  ~~~~~~~^~~~~~
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:726:59: error: cannot convert 'float_t*' {aka 'long double*'} to 'float*'
  726 |                 if (_parseNumber(&satuation, &brightness, &tb) && brightness && *brightness == '%') {
      |                                                           ^~~
      |                                                           |
      |                                                           float_t* {aka long double*}
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:106:73: note:   initializing argument 3 of 'bool _parseNumber(const char**, const char**, float*)'
  106 | static bool _parseNumber(const char** content, const char** end, float* number)
      |                                                                  ~~~~~~~^~~~~~
```

The issue was introduced in https://github.com/thorvg/thorvg/commit/0c6395cbea7495b5284cb33792798324bcc4f7da.

(If this is not the proper target branch, let me know, or feel free to merge this manually.)

### CODE REVIEW

**Review by mgrudzinska — APPROVED** [review]
I was sure I've already changed this at some point, but apparently I didn't :D

**Review by hermet — APPROVED** [review]

**Comment by akien-mga** [comment]
Could this be backported to the `0.13` releases?

We had this patch downstream but it was reverted by mistake when updating to 0.13.7, breaking the build again.

**Comment by hermet** [comment]
> Could this be backported to the `0.13` releases?
> 
> We had this patch downstream but it was reverted by mistake when updating to 0.13.7, breaking the build again.
> 
> (I'm still confused about whether there's any public branch releases are made from, as it seems this patch didn't make it to 0.13.7 despite being merged in `v0.13.x` prior to its release.)

@akien-mga Hello, I just noticed you sent your patch directly to the v0.13.x branch. In the next time, please send patches to the `main` branch. All necessary patches from `main` will be synced to the `release` branch (v0.13.x) through our release process.

By the way, I  just confirmed the fix must be in `main` and `v0.13.x`. Could you please double-check it?

image

**Comment by capnm** [comment]
@hermet :
main
git grep "float th, ts, tb;"
src/loaders/svg/tvgSvgLoader.cpp:712:        float th, ts, tb;
25370f438e19d9f6ae7471f0056d73253a0507db

git co origin/v0.13.x
git grep "float th, ts, tb;"
src/loaders/svg/tvgSvgLoader.cpp:712:        float th, ts, tb;
30aa742b26e35e170f927c8e5ebdaa68dea6f48f

**Comment by akien-mga** [comment]
It was fixed in main with 8c04b9d65ecd6503f9d7b4b45aae34f9552eda71 - but that's weeks before my PR to `v0.13.x`, so that still raises the question of how can I help ensure that a fix gets included in the next patch release, if the source branch isn't available to contribute to?

**Comment by hermet** [comment]
@akien-mga In ThorVG, the main idea is to push fixes/enhancements into the main (development) branch first. Then all necessary patches will be cherry-picked to the release branch (v0.13.x) during the weekly micro version update.

- **main (development branch)**: This branch can be unstable and is for ongoing development with aggressive updates.
- **v0.13.x (v0.13 release branch)**: Only verified patches (bug fixes and necessary enhancements since v0.13.0) will be merged here from the main branch.

**Comment by akien-mga** [comment]
That makes sense yes. I guess the `v0.13.x` branch is force pushed when making new releases?

Because my PR was merged in `v0.13.x` to fix a bug which had already been fixed in `main` in a commit of a bigger scope, so it made sense to me to hotfix it in `v0.13.x` with a dedicated PR. But I see my commit isn't in `v0.13.x` anymore, and the bug was finally fixed when 8c04b9d was cherry-picked.

Next time I'll open an issue instead if there's a `v0.13.x` specific bug that I'd like fixed in priority (e.g. by cherry-picking the commit that fixed it in `main`, or letting you do a more surgical hotfix).
